name: Makefile CI

on:
  push:
    branches: [ "linux-msft-wsl-6.6.y" ]
  pull_request:
    branches: [ "linux-msft-wsl-6.6.y" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev cpio

    - name: build
      run:  make KCONFIG_CONFIG=Microsoft/config-wsl -j$(nproc)

    - name: List working directory contents
        run: ls -alh /home/runner/work/


