name: Makefile CI

on:
  push:
    branches: [ "linux-msft-wsl-6.6.y" ]
  pull_request:
    branches: [ "linux-msft-wsl-6.6.y" ]

jobs:
  wsl-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 查看工作目录
      run: ls ./

    - name: 安装依赖
      run: sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev cpio

    - name: 编译
      run: make KCONFIG_CONFIG=Microsoft/config-wsl -j$(nproc)

    - name: 上传编译文件
      uses: actions/upload-artifact@v3
      with:
       name: build-artifact
       path: /home/runner/work/WSL2-Linux-Kernel/WSL2-Linux-Kernel/build/

