name: Makefile CI

on:
  push:
    branches: [ "linux-msft-wsl-6.6.y" ]
  pull_request:
    branches: [ "linux-msft-wsl-6.6.y" ]

jobs:
  wsl-build:

    runs-on: ubuntu-latest

    steps:

    - name: 上传编译文件
      uses: actions/upload-artifact@v3
      with:
       name: build-artifact
       path: /home/runner/work/WSL2-Linux-Kernel/WSL2-Linux-Kernel/

